name: Check & fix styling

on: [push]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          run: ${{ github.head_ref }}

      - name: Run PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix . --config=.trustenterprises.php_cs

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Fix styling
